<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\DandyEventStore.Persistence.Sql\DandyEventStore.Persistence.Sql.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentMigrator.Extensions.Postgres" />
      <PackageReference Include="FluentMigrator.Runner.Postgres" />
      <PackageReference Include="Npgsql" />
    </ItemGroup>

</Project>
