<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentMigrator.Runner.SQLite" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DandyEventStore.Persistence.Sql\DandyEventStore.Persistence.Sql.csproj" />
  </ItemGroup>
</Project>
