<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="Testcontainers.PostgreSql"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DandyEventStore.Persistence.Sql.Npgsql\DandyEventStore.Persistence.Sql.Npgsql.csproj" />
      <ProjectReference Include="..\DandyEventStore.Serialization.SystemTextJson\DandyEventStore.Serialization.SystemTextJson.csproj" />
    </ItemGroup>

</Project>