<Project>
    
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageVersion Include="Dapper" Version="2.1.79" />
        <PackageVersion Include="FluentMigrator.Runner.Core" Version="8.0.1" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
        <PackageVersion Include="Npgsql" Version="10.0.3" />
    </ItemGroup>
    
</Project>
